### ISSUE TITLE
Description Field Missing from Ajax Post

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#14]
There is a hidden form field 
<input type="hidden" name="description" value="WWISGREG" />

It can be found at line 329 in eway.html and line 326 in eway-expanded.html

Can you please ensure it is included in the ajax post as it needs to appear in the eway transaction details as the client needs it to differentiate these transactions from others.

**Comment by anhnt** [comment]
Yes, this field should be post within the ajax call. Here is example form data:
    AddressLine1: "Nguyen Xa - Vu Thu"
AddressLine2: ""
City: "Thai Binh"
Country: "Vietnam"
Postcode: "415273"
State: "Thai Binh"
countryCode: "au"
currencyCode: "AUD"
cvn: "eCrypted:KT3/tejU676RVxPoIaw3XSZT7KaRb+7J4GLtvr4Z8Y6/iv/FXtuIesJpIaWhqPKccPka2Hh6/Zm8orNe55Wiu8WGdYFo6X4kbPS1Uzh9DCy665xRkkeuH/64gPXaiis+NU7IUtbVWWhsRAW1QH94cRm5FG0BfSrPGxL2Q5x0gk6c2S0k5CMG/kwljO44ILB/D74PDOLuOCw3vFoWrPz89QIT6CKBTtI9ZI1jnmo1pP1eTp/DWEKo5qVXjwkEQXu3XAZLpUj52MICUBY271vPcZkUJ66qk0iMiaeEqQ1osJYjicDQvSSrXyMYDIJjsr/JE7HYjWTCcxZFu2i4qcsjKw=="
description: "WWISGREG"
email: "anhnt38@gmail.com"
expiryMonth: "01"
expiryYear: "12"
firstName: "Anh"
frequency: "MONTHLY"
immediate: true
multiples: 1
name: "Jo Blogs"
number: "eCrypted:XWUT41KISJbMtfU2HB40ekdPM/P6IOibE8qB1dTtbq4Ho5HMUw4iYwLYWnQ3vOjrKqZrKZza9hyrikFKL/V6kcRbSlJFCco31dZkh4eV0UzMCmGlcG267DW06OjwBjKmembAcPEEVyD6wZvmNOMIkTnwlePO0Hs3xVBTHVPVnJeLHzsY4MT/d3LVq6L1wFq6+nkKdelttEiiPxib8AuL3OnKXkv6CCN2CHtJdGDDOeTE58z4fYhK2uLDAxL2u9awXHHlTyT86YQ2ZfjvZpAc8Yc1bCgJH9FgBLotaVpD0uvYkegj4xB0hXjAQm97lOiR9cCepidE2F+9sXAzMCzBFQ=="
optins: "Petition-Main-Email,Petition-Main-SMS"
phone: "+84936584666"
surName: "Nguyen"
totalAmount: 25
websiteBranch: "amcs/version3-facebooktest"

**Comment by jasonlewis72** [comment]
No worries – thanks for confirming
