### ISSUE TITLE
504 error text addition

### ISSUE THREAD

**Issue by Jamespublic** [jasonlewis72/amcs#21]
I received the following error on one test: ![504 error screenshot](https://cloud.githubusercontent.com/assets/1096108/7129250/ec0e0898-e2a0-11e4-89e3-4208ad349eca.png)

Could we please add the following line to the end of this error (as it worked for me when I resubmitted) after a paragraph break.:

Please try submitting your donation again.

**Comment by jasonlewis72** [comment]
Hi Brad - Anh has added a screen grab of the error message

**Comment by jasonlewis72** [comment]
James - A 504 error is a gateway timeout error. This is the response returned from eway. This error means that we have connected to them successfully, but some internal process at eway has failed to complete in time and the eway server has returned this response to complete transaction (not the payment transaction, the communication transaction between kademi and eway)

IF that doesnt make sense, let me know and I'll call to explain
