### ISSUE TITLE
No card error

### ISSUE THREAD

**Issue by Jamespublic** [jasonlewis72/amcs#22]
Not sure what's going on with the below. You can see the error and the details that I put in. These are the correct test card details. 

The transaction DID then work when I changed the donation amount from $23.56. So it appears that that 'other amount' field still has some bugs - and the error message it's spitting out is incorrectly identifying the card as the issue. Could you please look into this?

![no card error](https://cloud.githubusercontent.com/assets/1096108/7129383/faec6920-e2a2-11e4-93a7-97b4baf570c8.png)

**Comment by jasonlewis72** [comment]
In the sandbox - each cents value will generate a diffferent response error - it allows you to test different error messages. This is by design in the sandbox - this will be different in the live environment
