### ISSUE TITLE
Submission wait visual timer

### ISSUE THREAD

**Issue by Jamespublic** [jasonlewis72/amcs#23]
It's a good feature that the donation submission button changes to "Processing" when it's processing, but sometimes (especially if there's a submission error on the way), it can take 20 seconds or more to get a response.

In light of this, is there something we can have come up over the page when it's processing? A rotating circle or hourglass that says "Payment processing, please wait" or something?

**Comment by anhnt** [comment]
I've added a progress modal for this. @jasonlewis72 can you please check it?

**Comment by jasonlewis72** [comment]
James - Can you please review and let me know if this is ok

**Comment by Jamespublic** [comment]
This looks great, thanks.
