### ISSUE TITLE
Updated validation rules

### ISSUE THREAD

**Issue by Jamespublic** [jasonlewis72/amcs#27]
Please add a list of errors to the alertbox that comes up when form doesn't validate. Ie: 

------
Sorry, some form fields are invalid. Please check fields outlined in red for the following errors:

- Error 1
- Error 2
- Error 3

------

Also, please make validation rules for the following fields as below.

Rule: ‘Other amount’: Validates only if there is (a) NO decimal point, or (b) a decimal point with TWO digits after it.
Invalid message: ‘Other amount’ field must be written in (a) whole dollars or (b) dollars and cents

Rule: CC expiry: Validates only if expiry date is on or after current month
Invalid message: Credit card expiry date must be this current month or after.

Rule: Phone field: Only accepts numerals
Invalid message: Phone field only accepts numbers. Please remove any letters or punctuation, including characters such as (, ) or -

**Comment by jasonlewis72** [comment]
Anh - Can you please review these and if necessary lets discuss if it is a big issue.
