### ISSUE TITLE
Donation thank you emails

### ISSUE THREAD

**Issue by Jamespublic** [jasonlewis72/amcs#28]
I've created new automations for thank you emails for (a) one-off donations and (b) regular donations. Could you please link these with the appropriate donation type?

I'm not sure how we'll get them to fire, but it would probably be handy to have new separate groups for (a) new one-off donors and (b) new regular donors. Would we do it that way?

We also need to merge in the following details into the receipt sections at the bottom of both emails:

- Surname
- Donation amount
- Receipt number
- Donation date

PLEASE NOTE: The regular donation thank you email also merges the amount higher up in the email body, just under the salutation.

**Comment by jasonlewis72** [comment]
Brad 
James requires Kademi to send emails once payments are made. This would need to be for once off and recurring payments 

The emails need to contact the summary transaction details

Surname:
Frequency: Once Off/Recurring
Donation Amount
Receipt No/Transaction ID
Transaction Date

Could you please implement this.

**Comment by jasonlewis72** [comment]
These have now been actioned
