### ISSUE TITLE
Transaction Information Update

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#30]
URL: http://admin.amcs.olhub.com/payments/
Tab: Transactions

Hi Brad,

As discussed this morning, could you please update the Transactions View page 
- Include Payment Amount and Surname Details
- Either hide or Place a label against Recurring Payment entries to indicate Account Creation for Recurring. I think if they are going to be included there needs to be a little bit more information to explain them so that the client does think they are incomplete transactions.

**Comment by bradmac** [comment]
"Either hide or Place a label against Recurring Payment entries to indicate Account Creation for Recurring. I think if they are going to be included there needs to be a little bit more information to explain them so that the client does think they are incomplete transactions." - DONE
