### ISSUE TITLE
Inconsistent fonts in forms

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#34]
Please make these consistent (note how it goes between small black text, and bigger grey text).

3 sizes are displayed in the respective images

![desktop](https://cloud.githubusercontent.com/assets/3991284/7292008/ef9b43ea-e9da-11e4-9bbc-c4186e2a0847.gif)
![mobile](https://cloud.githubusercontent.com/assets/3991284/7292009/ef9b980e-e9da-11e4-9cee-4ee21d5f3e15.gif)
![tablet](https://cloud.githubusercontent.com/assets/3991284/7292010/efa09fa2-e9da-11e4-9766-22c348013113.gif)

**Comment by anhnt** [comment]
Fixed!

**Comment by jasonlewis72** [comment]
The Expiry Date MM and YY and Country Dropdowns look like they are a different color to the other fields
