### ISSUE TITLE
Random line/s in page footer

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#36]
Please remove. This occurs on both landing and thank you page.

![line](https://cloud.githubusercontent.com/assets/3991284/7292052/48c559d8-e9db-11e4-9a53-a9c7cdffb451.gif)

**Comment by anhnt** [comment]
fixed!

**Comment by jasonlewis72** [comment]
Hi Anh - This is fixed in the payment pages but still remains in the thanks page - sorry did mention it above but should have amde it clearer
