### ISSUE TITLE
Once off vs Recurring Payments

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#40]
Hi Anh,

We currently don't have a list of those people making a once off vs recurring payment.

Can you please create 2 groups 
- Once Off Payment
- Recurring Payment

and pass an optin value that puts each person into either one of these groups when they make a payment so that we generate a list of each group

**Comment by anhnt** [comment]
These groups have added and optins. Please check it @jasonlewis72

**Comment by jasonlewis72** [comment]
People who make payments are now added to 1 of 2 groups 
- Once off Payment Group
- Recurring Payment Group

**Comment by lachlanrdale** [comment]
Lovely, thanks Jason.


________________________________
