### ISSUE TITLE
Thanks page email share text update

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#43]
Hey Jason, I think this got missed in the bugs I sent over the other day.

This copy is missing the page URL.

Instead reads "<page URL>?utm_source=tqpgshem”

There are also 10 or so extra line breaks that should be removed at the end.

Finally, there are a few strange characters in the email too, so I’ll repost the Email Share Text below with those characters removed.

Please update with the text below:

=====

i,

You've probably heard that our Great Barrier Reef is under more threat than ever from dirty industry and bad government policy. 

The situation is getting more serious every day, but there is something we can do about it, right now.

I've just helped the Australian Marine Conservation Foundation with its campaign to stop five new port expansions up and down the Great Barrier Reef coast. Get the full low-down here: 

https://reef.marineconservation.org.au/donate.html?utm_campaign=AMCSREEF&utm_medium=email&utm_source=tqpage

Environment Minister Greg Hunt is the key player in all of this. And the good news is he's on the back foot after the recent change of Government in Queensland.

The federal government in Canberra is super-sensitive to public opinion right now, and public opinion says that port expansion in the world's most significant marine park just doesn't make sense.

The expanded ports will be used to load huge coal ships that will cut across the Reef along deep channels gouged through the seabed in the Reef's World Heritage waters. 

It will be an environmental disaster - and it doesn’t even make economic sense. The global demand for coal is tapering off, and current Queensland coal ports aren't even being used to capacity.

It's just so short sighted. We’re fortunate enough to have the world's most amazing natural wonder right on our doorstep. It provides thousands of jobs and billions of dollars in sustainable tourism every year. 

We'd be crazy to risk all that for the short-term profit of vested interests.

The Great Barrier Reef belongs to all Australians - not dirty industry. It's up to us to say enough is enough. That's why I've done my bit by making a donation to the Australian Marine Conservation Society. AMCS is the original Reef campaigner, responsible for its protection as a Marine Park 40 years ago.

AMCS do a fantastic job but there still so much to do and so many more people to get on board.

Please take a minute to get more of the story:

https://reef.marineconservation.org.au/donate.html?utm_campaign=AMCSREEF&utm_medium=email&utm_source=tqpage

Thanks,

**Comment by jasonlewis72** [comment]
Hi Lachlan - This has been updated.

One thing I have noticed - the url is /donate.html

What is the pagename for the eway page (donate.html ?)
What is the name for the expanded eway page?

**Comment by lachlanrdale** [comment]
Hey Jason, here's what I had originally:

reef.marineconservation.org.au/sign — petition landing
reef.marineconservation.org.au/share — petition thank you
reef.marineconservation.org.au/support — fundraising landing
reef.marineconservation.org.au/thanks — fundraising thank you

Shall we therefore call the pages:

https://reef.marineconservation.org.au/support.html
https://reef.marineconservation.org.au/thanks.html

And therefore the updated text should be:

---------

Hi,

You've probably heard that our Great Barrier Reef is under more threat than ever from dirty industry and bad government policy.

The situation is getting more serious every day, but there is something we can do about it, right now.

I've just helped the Australian Marine Conservation Foundation with its campaign to stop five new port expansions up and down the Great Barrier Reef coast. Get the full low-down here:

https://reef.marineconservation.org.au/support.html?utm_campaign=AMCSREEF&utm_medium=email&utm_source=tqpage

Environment Minister Greg Hunt is the key player in all of this. And the good news is he's on the back foot after the recent change of Government in Queensland.

The federal government in Canberra is super-sensitive to public opinion right now, and public opinion says that port expansion in the world's most significant marine park just doesn't make sense.

The expanded ports will be used to load huge coal ships that will cut across the Reef along deep channels gouged through the seabed in the Reef's World Heritage waters.

It will be an environmental disaster - and it doesn’t even make economic sense. The global demand for coal is tapering off, and current Queensland coal ports aren't even being used to capacity.

It's just so short sighted. We’re fortunate enough to have the world's most amazing natural wonder right on our doorstep. It provides thousands of jobs and billions of dollars in sustainable tourism every year.

We'd be crazy to risk all that for the short-term profit of vested interests.

The Great Barrier Reef belongs to all Australians - not dirty industry. It's up to us to say enough is enough. That's why I've done my bit by making a donation to the Australian Marine Conservation Society. AMCS is the original Reef campaigner, responsible for its protection as a Marine Park 40 years ago.

AMCS do a fantastic job but there still so much to do and so many more people to get on board.

Please take a minute to get more of the story:

https://reef.marineconservation.org.au/support.html?utm_campaign=AMCSREEF&utm_medium=email&utm_source=tqpage

Thanks,

**Comment by jasonlewis72** [comment]
This has been updated
