### ISSUE TITLE
Thanks page displaying incorrectly at smaller sizes

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#44]
The dolphin image is disappearing on our thanks page when reduced to smaller window sizes.

Please investigate. 
![screen shot 2015-04-28 at 9 37 23 am](https://cloud.githubusercontent.com/assets/12091538/7360116/53bee720-ed8a-11e4-9906-9747047971bf.png)
![screen shot 2015-04-28 at 9 37 13 am](https://cloud.githubusercontent.com/assets/12091538/7360117/53c1af96-ed8a-11e4-8e9f-19af3440de4f.png)

**Comment by anhnt** [comment]
This has been resolved. Please check

**Comment by lachlanrdale** [comment]
Verified. Cheers!

**Comment by anhnt** [comment]
Cool! Can you please close it :)
