### ISSUE TITLE
Setting AMCS' EWAY gateway live

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#46]
Hey Jason, as discussed I'd appreciate it if you can hook up AMCS' EWAY account details:

**Comment by anhnt** [comment]
@jasonlewis72 can you please take care of this issue since the eway account should be change when this page goes live?

**Comment by jasonlewis72** [comment]
Once we get final approval on the page, these details will be updated

**Comment by lachlanrdale** [comment]
@jasonlewis72 Good to go live! Let me know when it's hooked up.

**Comment by lachlanrdale** [comment]
@jasonlewis72 @bradmac We’re good to set this gateway live (so I can launch this page).

Please let me know when you can do this. We’re supposed to be blasting an email around 1pm.

**Comment by jasonlewis72** [comment]
As discussed this is live now
