### ISSUE TITLE
Deployment of Version 4

### ISSUE THREAD

**Issue by jasonlewis72** [jasonlewis72/amcs#47]
Hi Lachlan
Version 4 of the site has been deployed.

You can now access the pages on

http://reef.marineconservation.org.au/eway.html
http://reef.marineconservation.org.au/eway-expanded.html
http://reef.marineconservation.org.au/index.html (petition page)

**Comment by lachlanrdale** [comment]
I think the specific URLs have to be used to log goals, no?

IE: we should push these to the final live URLs

**Comment by lachlanrdale** [comment]
Can I also confirm what this 'expanded' page version is?

The original developer brief had two different donation form behaviours (vertical expanding, and horizontal scrolling). We've clearly missed the latter version, so we should just have a single version of the landing page, no?

**Comment by jasonlewis72** [comment]
Yes - I will rename that to donate.html

**Comment by lachlanrdale** [comment]
Sorry, Jason, to confirm what I wrote in an accompanying issue:

Hey Jason, here's what I had originally:

reef.marineconservation.org.au/sign — petition landing
reef.marineconservation.org.au/share — petition thank you
reef.marineconservation.org.au/support — fundraising landing
reef.marineconservation.org.au/thanks — fundraising thank you

Shall we therefore call the pages:

https://reef.marineconservation.org.au/support.html
https://reef.marineconservation.org.au/thanks.html

**Comment by lachlanrdale** [comment]
Give me one moment - I'll confirm what our pre-set up ads are pointing to...

**Comment by jasonlewis72** [comment]
This has been updated - let me know if it changes

**Comment by lachlanrdale** [comment]
Thanks Jason, I'll just have to do a sweep of our various share collateral to make sure this works. Will add any changes/updates in a new issue.

**Comment by jasonlewis72** [comment]
Ok - I'll close this issue for now then
