### ISSUE TITLE
Updating error messages for EWAY gateway

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#48]
Requesting some error message updates for our EWAY bridge.

The first one seems to be a website error message (not EWAY). **Please let me know if there is a list of these errors for me to customise.**

Here are the messages I'd like updated (I've got the current error message first, followed by the requested update):

Some field is invalid. Please check again!
“Some fields contain invalid entries. Please check your information, and try again.”

Invalid EWAY_CARDNUMBER 
“Please enter a valid credit card number.”

Invalid Card Number
“Please enter a valid credit card number.”

Invalid EWAY_CARDEXPIRYYEAR
“Please enter a valid expiry date.”

Invalid Customer Phone
“Please enter a valid phone number.”

Invalid Amount
“Invalid donation amount. Please check your information, and try again.”

Expired Card
“Your card seems to be expired. Please check your information, and try again.”

No Credit Account
“There appears to be no credit on your account. Please contact your bank.”

Insufficient Funds
“There appears to be no credit on your account. Please contact your bank.”

Stolen Card
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspected Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Exceeds Withdrawal Limit
“There seems to be an issue processing your credit card. Please contact your bank.”

Amex Declined
“There seems to be an issue processing your credit card. Please contact your bank.”

Challenged Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Country Match Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

High Risk Country Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Anonymous Proxy Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Transparent Proxy Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Undefined Fraud Error
“There seems to be an issue processing your credit card. Please contact your bank.”

Risk Score Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspicious Customer First Name
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspicious Customer Last Name
“There seems to be an issue processing your credit card. Please contact your bank.”

Invalid Billing Street
“Invalid street address detected. Please check your entries and try again.”

EWAY_CARDHOLDERNAME Required
“Please check your credit card details and try again. If problems persist please contact your bank.”

EWAY_CARDNUMBER Required
“Please enter a valid credit card number and try again.”

EWAY_CARDCVN Required
“Please enter a valid CVN number and try again.”

Invalid Expiry Date
“Please enter a valid expiry date and try again.”

Invalid Issue Number
“Please check your credit card details and try again. If problems persist please contact your bank.”

Here is Brad's full list of EWAY error messages:

    static {
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("A2000", "Transaction Approved");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("A2008", "Honour With Identification");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("A2010", "Approved For Partial Amount");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("A2011", "Approved, VIP");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("A2016", "Approved, Update Track 3");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4401", "Refer to Issuer");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4402", "Refer to Issuer, special");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4403", "No Merchant");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4404", "Pick Up Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4405", "Do Not Honour");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4406", "Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4407", "Pick Up Card, Special");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4409", "Request In Progress");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4412", "Invalid Transaction");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4413", "Invalid Amount");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4414", "Invalid Card Number");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4415", "No Issuer");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4419", "Re-enter Last Transaction");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4421", "No Action Taken");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4422", "Suspected Malfunction");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4423", "Unacceptable Transaction Fee");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4425", "Unable to Locate Record On File");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4430", "Format Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4431", "Bank Not Supported By Switch");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4433", "Expired Card, Capture");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4434", "Suspected Fraud, Retain Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4435", "Card Acceptor, Contact Acquirer, Retain Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4436", "Restricted Card, Retain Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4437", "Contact Acquirer Security Department, Retain Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4438", "PIN Tries Exceeded, Capture");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4439", "No Credit Account");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4440", "Function Not Supported");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4441", "Lost Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4442", "No Universal Account");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4443", "Stolen Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4444", "No Investment Account");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4451", "Insufficient Funds");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4452", "No Cheque Account");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4453", "No Savings Account");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4454", "Expired Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4455", "Incorrect PIN");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4456", "No Card Record");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4457", "Function Not Permitted to Cardholder");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4458", "Function Not Permitted to Terminal");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4459", "Suspected Fraud");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4460", "Acceptor Contact Acquirer");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4461", "Exceeds Withdrawal Limit");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4462", "Restricted Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4463", "Security Violation");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4464", "Original Amount Incorrect");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4466", "Acceptor Contact Acquirer, Security");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4467", "Capture Card");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4475", "PIN Tries Exceeded");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4482", "CVV Validation Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4490", "Cut off In Progress");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4491", "Card Issuer Unavailable");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4492", "Unable To Route Transaction");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4493", "Cannot Complete, Violation Of The Law");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4494", "Duplicate Transaction");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4495", "Amex Declined");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4496", "System Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4497", "MasterPass Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4498", "PayPal Create Transaction Error");
        TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4499", "Invalid Transaction for Auth/Void");
    }

    static {
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7000", "Undefined Fraud Error");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7001", "Challenged Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7002", "Country Match Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7003", "High Risk Country Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7004", "Anonymous Proxy Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7005", "Transparent Proxy Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7006", "Free Email Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7007", "International Transaction Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7008", "Risk Score Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7009", "Denied Fraud");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F7010", "Denied by PayPal Fraud Rules");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9010", "High Risk Billing Country");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9011", "High Risk Credit Card Country");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9012", "High Risk Customer IP Address");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9013", "High Risk Email Address");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9014", "High Risk Shipping Country");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9015", "Multiple card numbers for single email address");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9016", "Multiple card numbers for single location");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9017", "Multiple email addresses for single card number");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9018", "Multiple email addresses for single location");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9019", "Multiple locations for single card number");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9020", "Multiple locations for single email address");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9021", "Suspicious Customer First Name");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9022", "Suspicious Customer Last Name");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9023", "Transaction Declined");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9024", "Multiple transactions for same address with known credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9025", "Multiple transactions for same address with new credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9026", "Multiple transactions for same email with new credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9027", "Multiple transactions for same email with known credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9028", "Multiple transactions for new credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9029", "Multiple transactions for known credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9030", "Multiple transactions for same email address");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9031", "Multiple transactions for same credit card");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9032", "Invalid Customer Last Name");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9033", "Invalid Billing Street");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9034", "Invalid Shipping Street");
        BEAGLE_FRAUD_RESPONSE_MAP.put("F9037", "Suspicious Customer Email Address");
    }

    static {
        SYSTEM_RESPONSE_MAP.put("S5000", "System Error");
        SYSTEM_RESPONSE_MAP.put("S5011", "PayPal Connection Error");
        SYSTEM_RESPONSE_MAP.put("S5012", "PayPal Settings Error");
        SYSTEM_RESPONSE_MAP.put("S5085", "Started 3dSecure");
        SYSTEM_RESPONSE_MAP.put("S5086", "Routed 3dSecure");
        SYSTEM_RESPONSE_MAP.put("S5087", "Completed 3dSecure");
        SYSTEM_RESPONSE_MAP.put("S5088", "PayPal Transaction Created");
        SYSTEM_RESPONSE_MAP.put("S5099", "Incomplete (Access Code in progress/incomplete)");
        SYSTEM_RESPONSE_MAP.put("S5010", "Unknown error returned by gateway");
    }

    static {
        VALIDATION_RESPONSE_MAP.put("V6000", "Validation error");
        VALIDATION_RESPONSE_MAP.put("V6001", "Invalid CustomerIP");
        VALIDATION_RESPONSE_MAP.put("V6002", "Invalid DeviceID");
        VALIDATION_RESPONSE_MAP.put("V6003", "Invalid Request PartnerID");
        VALIDATION_RESPONSE_MAP.put("V6004", "Invalid Request Method");
        VALIDATION_RESPONSE_MAP.put("V6010", "Invalid TransactionType, account not certified for eCome only MOTO or Recurring available");
        VALIDATION_RESPONSE_MAP.put("V6011", "Invalid Payment TotalAmount");
        VALIDATION_RESPONSE_MAP.put("V6012", "Invalid Payment InvoiceDescription");
        VALIDATION_RESPONSE_MAP.put("V6013", "Invalid Payment InvoiceNumber");
        VALIDATION_RESPONSE_MAP.put("V6014", "Invalid Payment InvoiceReference");
        VALIDATION_RESPONSE_MAP.put("V6015", "Invalid Payment CurrencyCode");
        VALIDATION_RESPONSE_MAP.put("V6016", "Payment Required");
        VALIDATION_RESPONSE_MAP.put("V6017", "Payment CurrencyCode Required");
        VALIDATION_RESPONSE_MAP.put("V6018", "Unknown Payment CurrencyCode");
        VALIDATION_RESPONSE_MAP.put("V6021", "EWAY_CARDHOLDERNAME Required");
        VALIDATION_RESPONSE_MAP.put("V6022", "EWAY_CARDNUMBER Required");
        VALIDATION_RESPONSE_MAP.put("V6023", "EWAY_CARDCVN Required");
        VALIDATION_RESPONSE_MAP.put("V6033", "Invalid Expiry Date");
        VALIDATION_RESPONSE_MAP.put("V6034", "Invalid Issue Number");
        VALIDATION_RESPONSE_MAP.put("V6035", "Invalid Valid From Date");
        VALIDATION_RESPONSE_MAP.put("V6040", "Invalid TokenCustomerID");
        VALIDATION_RESPONSE_MAP.put("V6041", "Customer Required");
        VALIDATION_RESPONSE_MAP.put("V6042", "Customer FirstName Required");
        VALIDATION_RESPONSE_MAP.put("V6043", "Customer LastName Required");
        VALIDATION_RESPONSE_MAP.put("V6044", "Customer CountryCode Required");
        VALIDATION_RESPONSE_MAP.put("V6045", "Customer Title Required");
        VALIDATION_RESPONSE_MAP.put("V6046", "TokenCustomerID Required");
        VALIDATION_RESPONSE_MAP.put("V6047", "RedirectURL Required");
        VALIDATION_RESPONSE_MAP.put("V6048", "CheckoutURL Required when CheckoutPayment specified");
        VALIDATION_RESPONSE_MAP.put("​V6049", "Invalid Checkout URL");
        VALIDATION_RESPONSE_MAP.put("V6051", "Invalid Customer FirstName");
        VALIDATION_RESPONSE_MAP.put("V6052", "Invalid Customer LastName");
        VALIDATION_RESPONSE_MAP.put("V6053", "Invalid Customer CountryCode");
        VALIDATION_RESPONSE_MAP.put("V6058", "Invalid Customer Title");
        VALIDATION_RESPONSE_MAP.put("V6059", "Invalid RedirectURL");
        VALIDATION_RESPONSE_MAP.put("V6060", "Invalid TokenCustomerID");
        VALIDATION_RESPONSE_MAP.put("V6061", "Invalid Customer Reference");
        VALIDATION_RESPONSE_MAP.put("V6062", "Invalid Customer CompanyName");
        VALIDATION_RESPONSE_MAP.put("V6063", "Invalid Customer JobDescription");
        VALIDATION_RESPONSE_MAP.put("V6064", "Invalid Customer Street1");
        VALIDATION_RESPONSE_MAP.put("V6065", "Invalid Customer Street2");
        VALIDATION_RESPONSE_MAP.put("V6066", "Invalid Customer City");
        VALIDATION_RESPONSE_MAP.put("V6067", "Invalid Customer State");
        VALIDATION_RESPONSE_MAP.put("V6068", "Invalid Customer PostalCode");
        VALIDATION_RESPONSE_MAP.put("V6069", "Invalid Customer Email");
        VALIDATION_RESPONSE_MAP.put("V6070", "Invalid Customer Phone");
        VALIDATION_RESPONSE_MAP.put("V6071", "Invalid Customer Mobile");
        VALIDATION_RESPONSE_MAP.put("V6072", "Invalid Customer Comments");
        VALIDATION_RESPONSE_MAP.put("V6073", "Invalid Customer Fax");
        VALIDATION_RESPONSE_MAP.put("V6074", "Invalid Customer URL");
        VALIDATION_RESPONSE_MAP.put("V6075", "Invalid ShippingAddress FirstName");
        VALIDATION_RESPONSE_MAP.put("V6076", "Invalid ShippingAddress LastName");
        VALIDATION_RESPONSE_MAP.put("V6077", "Invalid ShippingAddress Street1");
        VALIDATION_RESPONSE_MAP.put("V6078", "Invalid ShippingAddress Street2");
        VALIDATION_RESPONSE_MAP.put("V6079", "Invalid ShippingAddress City");
        VALIDATION_RESPONSE_MAP.put("V6080", "Invalid ShippingAddress State");
        VALIDATION_RESPONSE_MAP.put("V6081", "Invalid ShippingAddress PostalCode");
        VALIDATION_RESPONSE_MAP.put("V6082", "Invalid ShippingAddress Email");
        VALIDATION_RESPONSE_MAP.put("V6083", "Invalid ShippingAddress Phone");
        VALIDATION_RESPONSE_MAP.put("V6084", "Invalid ShippingAddress Country");
        VALIDATION_RESPONSE_MAP.put("V6085", "Invalid ShippingAddress ShippingMethod");
        VALIDATION_RESPONSE_MAP.put("V6086", "Invalid ShippingAddress Fax");
        VALIDATION_RESPONSE_MAP.put("V6091", "Unknown Customer CountryCode");
        VALIDATION_RESPONSE_MAP.put("V6092", "Unknown ShippingAddress CountryCode");
        VALIDATION_RESPONSE_MAP.put("V6100", "Invalid EWAY_CARDNAME");
        VALIDATION_RESPONSE_MAP.put("V6101", "Invalid EWAY_CARDEXPIRYMONTH");
        VALIDATION_RESPONSE_MAP.put("V6102", "Invalid EWAY_CARDEXPIRYYEAR");
        VALIDATION_RESPONSE_MAP.put("V6103", "Invalid EWAY_CARDSTARTMONTH");
        VALIDATION_RESPONSE_MAP.put("V6104", "Invalid EWAY_CARDSTARTYEAR");
        VALIDATION_RESPONSE_MAP.put("V6105", "Invalid EWAY_CARDISSUENUMBER");
        VALIDATION_RESPONSE_MAP.put("V6106", "Invalid EWAY_CARDCVN");
        VALIDATION_RESPONSE_MAP.put("V6107", "Invalid EWAY_ACCESSCODE");
        VALIDATION_RESPONSE_MAP.put("V6108", "Invalid CustomerHostAddress");
        VALIDATION_RESPONSE_MAP.put("V6109", "Invalid UserAgent");
        VALIDATION_RESPONSE_MAP.put("V6110", "Invalid EWAY_CARDNUMBER");
        VALIDATION_RESPONSE_MAP.put("V6111", "Unauthorised API Access, Account Not PCI Certified");
        VALIDATION_RESPONSE_MAP.put("V6112", "Redundant card details other than expiry year and month");
        VALIDATION_RESPONSE_MAP.put("V6113", "Invalid transaction for refund");
        VALIDATION_RESPONSE_MAP.put("V6114", "Gateway validation error");
        VALIDATION_RESPONSE_MAP.put("V6115", "Invalid DirectRefundRequest, Transaction ID");
        VALIDATION_RESPONSE_MAP.put("V6116", "Invalid card data on original TransactionID");
        VALIDATION_RESPONSE_MAP.put("V6117", "Invalid CreateAccessCodeSharedRequest, FooterText");
        VALIDATION_RESPONSE_MAP.put("V6118", "Invalid CreateAccessCodeSharedRequest, HeaderText");
        VALIDATION_RESPONSE_MAP.put("V6119", "Invalid CreateAccessCodeSharedRequest, Language");
        VALIDATION_RESPONSE_MAP.put("V6120", "Invalid CreateAccessCodeSharedRequest, LogoUrl");
        VALIDATION_RESPONSE_MAP.put("V6121", "Invalid TransactionSearch, Filter Match Type");
        VALIDATION_RESPONSE_MAP.put("V6122", "Invalid TransactionSearch, Non numeric Transaction ID");
        VALIDATION_RESPONSE_MAP.put("V6123", "Invalid TransactionSearch,no TransactionID or AccessCode specified");
        VALIDATION_RESPONSE_MAP.put("V6124", "Invalid Line Items. The line items have been provided however the totals do not match the TotalAmount field");
        VALIDATION_RESPONSE_MAP.put("V6125", "Selected Payment Type not enabled");
        VALIDATION_RESPONSE_MAP.put("V6126", "Invalid encrypted card number, decryption failed");
        VALIDATION_RESPONSE_MAP.put("V6127", "Invalid encrypted cvn, decryption failed");
        VALIDATION_RESPONSE_MAP.put("V6128", "Invalid Method for Payment Type");
        VALIDATION_RESPONSE_MAP.put("V6129", "Transaction has not been authorised for Capture/Cancellation");
        VALIDATION_RESPONSE_MAP.put("V6130", "Generic customer information error");
        VALIDATION_RESPONSE_MAP.put("V6131", "Generic shipping information error");
        VALIDATION_RESPONSE_MAP.put("V6132", "Transaction has already been completed or voided, operation not permitted");
        VALIDATION_RESPONSE_MAP.put("V6133", "Checkout not available for Payment Type");
        VALIDATION_RESPONSE_MAP.put("V6134", "Invalid Auth Transaction ID for Capture/Void");
        VALIDATION_RESPONSE_MAP.put("V6135", "PayPal Error Processing Refund");
        VALIDATION_RESPONSE_MAP.put("V6140", "Merchant account is suspended");
        VALIDATION_RESPONSE_MAP.put("V6141", "Invalid PayPal account details or API signature");
        VALIDATION_RESPONSE_MAP.put("V6142", "Authorise not available for Bank/Branch");
        VALIDATION_RESPONSE_MAP.put("V6150", "Invalid Refund Amount");
        VALIDATION_RESPONSE_MAP.put("V6151", "Refund amount greater than original transaction");
        VALIDATION_RESPONSE_MAP.put("V6152", "Original transaction already refunded for total amount");
        VALIDATION_RESPONSE_MAP.put("V6153", "Card type not support by merchant");

    }

}

**Comment by lachlanrdale** [comment]
Hey @bradmac @jasonlewis72 - let me know if this is easy enough to set up. 

I'd love to have this live on the site in the next few hours.

**Comment by bradmac** [comment]
I dont think we can do "next few hours", but will aim to have it in today

**Comment by bradmac** [comment]
Just one thing, with this bit:
'Some field is invalid. Please check again!'

I think this is implemented in AMCS app code, so would be a job for @anhnt or @jasonlewis72

**Comment by lachlanrdale** [comment]
We're pushing live today - ideally sending out a bulk email at 1.30pm EST today to drive traffic to the site, so let me know how you go.

**Comment by bradmac** [comment]
Bruce is working on it now - https://github.com/Kademi/kademi-dev/issues/339

**Comment by lachlanrdale** [comment]
@bradmac Sure. Based on that job it looks complete -- but I cannot see error messages updated on the live site.

@jasonlewis72 Please let me know when you've updated that non-EWAY error message.

**Comment by bradmac** [comment]
the work is complete, but still needs to be deployed. We're just about to start the build and deploy process.

**Comment by bradmac** [comment]
That deploy is done now. Should be all good.

**Comment by lachlanrdale** [comment]
Apologies guys, another addition (just tested this, got an error message when entering the wrong security number):

TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4405", "Do Not Honour");

“Please check your credit card details and try again. If problems persist please contact your bank.”

**Comment by bradmac** [comment]
Working on it...

https://github.com/Kademi/kademi-dev/issues/339

**Comment by lachlanrdale** [comment]
Cheers @bradmac

**Comment by lachlanrdale** [comment]
Any issue with bulk email send to the page now? @bradmac

**Comment by skwidge** [comment]
Updated that message

**Comment by bradmac** [comment]
@lachlanrdale just the error code to update. Otherwise all good to go.
