### ISSUE TITLE
Update share details on landing/thanks page

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#49]
Hey Jason, just doing a sweep / check / update on share functionality (after we re-confirmed final page URLs):

**Landing page**

**Facebook**

Should be sharing the URL https://reef.marineconservation.org.au/support.html?utm_campaign=AMCSREEF&utm_medium=social&utm_source=facebook&utm_content=LDshare

* Will need to check OG Tags are populating correctly

**Google+**

Should be sharing the URL https://reef.marineconservation.org.au/support.html?utm_campaign=AMCSREEF&utm_medium=social&utm_source=gplus&utm_content=LDshare

* Will need to check OG Tags are populating correctly

**Twitter**

Update text to:

Step up the fight to save your #GreatBarrierReef from dirty industry and bad policy. Donate now to AMCS: bit.ly/help-save-your-reef

**Thanks page**

**Facebook**

Should be sharing the URL https://reef.marineconservation.org.au/support.html?utm_campaign=AMCSREEF&utm_medium=social&utm_source=facebook&utm_content=TQpage

* Will need to check OG Tags are populating correctly

**Twitter**

Update text to:

Step up the fight to save your #GreatBarrierReef from dirty industry and bad policy. Donate now to AMCS: bit.ly/-save-your-reef

Cheers,

**Comment by jasonlewis72** [comment]
These have been updated - PLease confirm they are correct

**Comment by lachlanrdale** [comment]
* Landing page - Twitter share needs the bit.ly link in the text (instead of full URL)

Other than that good to go!

**Comment by jasonlewis72** [comment]
If the bitly link goes in - the counter wont work

https://twittercommunity.com/t/tweet-share-button-counter-not-working/17286

**Comment by lachlanrdale** [comment]
Fair call. Leave it off then.
