### ISSUE TITLE
Automation set-up

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#51]
Hey Jason,

So I'd like to set up an automation which triggers:

* 14 days after signing a petition

Which is also:

* 7 days after receiving the engagement email automation

I've coded the email up here: 

http://admin.amcs.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign/

My question is:

* How can we set this automation up?

* How many people will it miss? IE: Will it only become active as an automation at that point? Which will mean I will just do a bulk send to ALL petition signers up until today?

Please let me know,

**Comment by lachlanrdale** [comment]
Hey guys, could you please verified these automations are set up correctly and are live?

http://admin.amcs.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign/

http://admin.amcs.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign(1)/

**Comment by jasonlewis72** [comment]
HI Lachlan

Ive had a look at the triggers - basically what I have taken the 7 day one, duplicated it but changed the trigger date to 14 days. As long as the initiating trigger event is the same one as the Day 7 one, it should fire 14 days after the initial firing of the trigger. 

Jason

**Comment by jasonlewis72** [comment]
Hi @bradmac - would you mind giving this a quick once over

**Comment by bradmac** [comment]
@jasonlewis72 they look correct, but what i suggest is you do a test so you see your event as a timer, and then force it to execute immediately
You can use the green play button on this page:
http://admin.amcs.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign/timerTriggers.html

That way you will see the email go immediately (well, after a minute or 2) and you can check the email has been templated correctly

**Comment by jasonlewis72** [comment]
Lachlan - Can you please confirm if this has been resolved

**Comment by lachlanrdale** [comment]
Hey @bradmac a quick follow up on this.

The automations seem to be firing:

![screen shot 2015-05-25 at 2 19 50 pm](https://cloud.githubusercontent.com/assets/12091538/7791736/4bce7c28-02e9-11e5-920c-03a595a9c15f.png)

But results (opens, clicks, etc) do not seem to be logged in this screen:

![screen shot 2015-05-25 at 2 19 42 pm](https://cloud.githubusercontent.com/assets/12091538/7791738/51c81a62-02e9-11e5-97f5-868800b8221c.png)

**Comment by lachlanrdale** [comment]
@bradmac @jasonlewis72 Could I please get a confirmation these automations are sending?

**Comment by bradmac** [comment]
Hi @lachlan, we've just found that the emails are getting rejected because of the too many recipients limit. We're looking into that now.

**Comment by lachlanrdale** [comment]
This doesn't make any sense to me, since this should have been an gradual and fairly consistent stream from 1 May.

This is a big issue on our end. It weakens our campaign, and our results.

I am going to switch off our Engagement and Fundraising automations, and send those communications as manual batches from hereon out.

Right now I need to understand which automations have been affected:

* Petition thank you
* Engagement email (seems like these have been failing)
* Fundraising launch (definitely failing)
* Fundraising chaser (definitely failing)
* One-off donation thank you
* Regular donation thank you

Further, I would like:

* A list of individuals who have receive our engagement automation (so I can determine who has missed out)

Will this error affect group email sends?

**Comment by bradmac** [comment]
We're currently working on resolving the issue, and then re-triggering the timers so the emails will resend. 

Can you please confirm that you do not want us to do that?

**Comment by lachlanrdale** [comment]
We do not want you to do that @bradmac 

We will take care of those sends via group/batch emails from hereon out.

**Comment by skwidge** [comment]
@lachlanrdale 
You can determine which automations have been affected and who has received them from the administration console.
You noted the mismatch between the triggers view and the email history view. Both are actually reporting correctly. The triggers all ran but the failed to send any emails.

You probably only need to look at the email history to find the information you need. [ e.g. http://amcs.admin.olhub.com/autoEmails/engagement-email-14-days-after-sign/#history-tab ] This will give you a full list of all emails that were successfully sent for each automation which you can download as a CSV file.

**Comment by skwidge** [comment]
@bradmac Hi Brad, I committed a fix for the group exclusion issue, you might want to review my last commit.

**Comment by lachlanrdale** [comment]
@skwidge @bradmac 

Can you please confirm which automations have been affected.

I'm afraid I don't have a lot of time to reconcile data.

**Comment by skwidge** [comment]
@lachlanrdale 
http://amcs.admin.olhub.com/autoEmails/engagement-email-14-days-after-sign/
http://amcs.admin.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign/
http://amcs.admin.olhub.com/autoEmails/fundraising-launch-email-14-days-after-sign%281%29/

All seem to have been affected to some degree
