### ISSUE TITLE
Thanks page title

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#52]
A very minor issue; page title doesn't appear to be displaying on the donation thanks page.

Please add when you can. I'm thinking "Thank goodness we can trust you | Australia Marine Conservation Society"

![screen shot 2015-04-30 at 3 29 32 pm](https://cloud.githubusercontent.com/assets/12091538/7406882/ced77962-ef4d-11e4-9b11-ba702d945137.png)

**Comment by jasonlewis72** [comment]
Hi Lachlan - This has been updated
