### ISSUE TITLE
Thanks emails no longer triggering

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#53]
Hey Jason,

Since we've updated the EWAY gateway details, the thanks emails are no longer triggering (both the one-off and recurring donation thanks emails).

Could you please investigate?

**Comment by lachlanrdale** [comment]
@jasonlewis72 Assume we have no love on this? Might have to delay bulk email until tomorrow (though I would very much like to get them out early in the day).

**Comment by jasonlewis72** [comment]
The issue was due to unexpected response codes coming back from eway. Brad has updated these now to accomodate all the options. This should now be working correctly

**Comment by lachlanrdale** [comment]
I've just tested 2x transactions (1x one off, 1x recurring) and have received thanks emails for neither.

Have you tested / verified?

**Comment by lachlanrdale** [comment]
@jasonlewis72 Hey Jason, any word on this issue? Have you successfully tested.

I would really like to start sending emails ASAP.

**Comment by bradmac** [comment]
@lachlanrdale we're looking into this now... should have some sort of answer soon

**Comment by lachlanrdale** [comment]
Thanks @bradmac - we do need to fix this and launch ASAP. 

Client was expecting launch yesterday (well, originally 4+ weeks ago). Thought this had already been resolved overnight.

**Comment by bradmac** [comment]
All good from my end. I've changed the trigger expression to key on the status, rather then the response codes.
