### ISSUE TITLE
Editing donations set-up

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#55]
Scenario:

Customer has accidentally signed up for a 'recurring payment', and would like to change their donation type to 'one-off.'

Where can our client edit this information?

I'll also be in contact about long term data. From what I understand (from talking with eWAY tech support this morning) Kademi is controlling donations via eWAY's Token Payments functionality. Obviously some of these recurring donors will be running for years to come -- so we'll have to talk about how those donations are handled long term.

**Comment by bradmac** [comment]
Our expectation is that a profile page will be required where a user can view their transaction history and change or cancel their donation settings. Requires creative.

**Comment by bradmac** [comment]
"Kademi is controlling donations via eWAY's Token Payments functionality" - Just FYI this was based on EWay's advice. We were told that the EWay managed recurring payments API was deprecated and we should use a timer to submit each scheduled payment. This was what caused the implementation delay.

**Comment by lachlanrdale** [comment]
@bradmac - what does 'requires creative' mean?

Our client has donors whose settings they need to update ASAP (recurring changed to one-off).

Is the current idea that Kademi's timer pushes donations to eWAY ongoing into the future? In a few months this project between AMCS and Pareto will end; but the donations will need to keep flowing.

**Comment by bradmac** [comment]
"what does 'requires creative' mean?" - to have a page for donors to manage their profile (eg email address) and donation settings (eg amount, frequency, etc) and to cancel and/or unsubscribe. All of these features are supported in Kademi but you would (presumably) want to specify the layout.

"Is the current idea that Kademi's timer pushes donations to eWAY ongoing into the future?" - Yes. EWay advised that we should not use the recurring payment API, and instead we should push donations to EWay with a token.

**Comment by lachlanrdale** [comment]
Who is to provide that creative? I don't recall discussing this point. 

If we were talking long-term objectives of the gateway functioning, we would want to hand over data / transactions to AMCS at the end of the project period, and they would want integration with their current process/es.

It sounds like the current solution would required AMCS to maintain an additional system (and subscription), which I don't they'll accept. I'll be meeting with this mid-week to talk over some data detail.

**Comment by jasonlewis72** [comment]
Lachlan - I'll call this afternoon to clarify this and discuss..

**Comment by lachlanrdale** [comment]
@jasonlewis72 @bradmac 

Just following this up.

The client has multiple supporters who accidentally made recurring instead of one-off payments.

How can I - or they - edit and update support donation information?

Cheers,

**Comment by bradmac** [comment]
You can cancel from here:
http://admin.amcs.olhub.com/payments/#recurring-tab

**Comment by lachlanrdale** [comment]
So, I'd like to:

* Keep a one-off donation
* Cancel any recurring donation

If I hit CANCEL, will that cancel all donations?

Cheers,

**Comment by bradmac** [comment]
When you cancel, that cancels the recurring task so no further transactions will be processed by it. But any transactions already processed will be unaffected.

**Comment by lachlanrdale** [comment]
Perfect. Thank you.
