### ISSUE TITLE
Quick text update

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#57]
On https://reef.marineconservation.org.au/sign.html

Please change all instances of "Abbott Point" to "Abbot Point" (there are three).

Cheers,

**Comment by lachlanrdale** [comment]
Is this update feasible @jasonlewis72 ?

I'd happily do it myself, but cannot see how to update.

**Comment by jasonlewis72** [comment]
Done

**Comment by lachlanrdale** [comment]
Champion. Thank you @jasonlewis72
