### ISSUE TITLE
Announcement box element on Fundraising landing page

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#58]
Hey @jasonlewis72 how's things?

Just wondering if you could make a small addition for us on the Fundraising landing page. We'd like to add an announcement box as below:

![amcs-fundraising-landingpage-matchedgiving](https://cloud.githubusercontent.com/assets/12091538/7791583/0cd18ab8-02e6-11e5-871d-ce1de249381f.jpg)

Ideally this could be a table, with text inside -- though, please note we'd like to remove the phrase "until 30 December 2015". Our designer can prepare this however is easiest for you (a layered PSD for instance).

While the job is quite small, I appreciate it is outside of scope, so let me know if you'd like some form of reimbursement.

Please let me know,

**Comment by jasonlewis72** [comment]
Hi Lachlan

This has been created.

http://version5.amcs.olhub.com/support.html

Let me know if there are any issues with it.

Jason

**Comment by lachlanrdale** [comment]
Hey Jason, just two quick points:

* Please remove the text "until December 2015"

* Could we have the width aligned with the image below for consistency?

![screen shot 2015-05-28 at 9 29 07 am](https://cloud.githubusercontent.com/assets/12091538/7849758/4af82706-051c-11e5-82b8-96a53237fedd.png)

**Comment by lachlanrdale** [comment]
Other than that it looks great, thank you.

**Comment by jasonlewis72** [comment]
Hi Lachlan - this has been updated - can you please review

**Comment by lachlanrdale** [comment]
Should this be live? @jasonlewis72

**Comment by lachlanrdale** [comment]
Can't see it

**Comment by lachlanrdale** [comment]
Dug around and found it in File Manager version/s. Looks good.

Let's do it.

**Comment by jasonlewis72** [comment]
Hi Lachlan - just to confirm - you would like to put this live? or do you need the link to review it

**Comment by lachlanrdale** [comment]
Please put it live.

Cheers.

**Comment by jasonlewis72** [comment]
Done - Can you please review and if correct close this issue

http://reef.marineconservation.org.au/support.html
