### ISSUE TITLE
Group email failed

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#59]
![screen shot 2015-05-26 at 4 45 56 pm](https://cloud.githubusercontent.com/assets/12091538/7806636/be7d74a8-03c6-11e5-995b-16a8a4c4e8f3.png)

At a bit of a loss. 

Attempted to send a group email to users who were supposed to have been sent a fundraising email, but were not due to a failure of Kademi's email automation system.

Now that group email send has failed.

**Comment by bradmac** [comment]
We had a server outage a short time ago, and that would stalled the job. I can restart it shortly...

**Comment by lachlanrdale** [comment]
@bradmac At this stage, I'd like to hold off sending the email (we see reduced response rates after 5pm).

Let me know which from that group (Flow5) were not sent, and we can look at sending again Thursday morning.

**Comment by bradmac** [comment]
The Flow5 email has not been sent at all.

**Comment by lachlanrdale** [comment]
Thanks @bradmac 

I'm off tomorrow. I will revisit this Thursday.

Cheers,
