### ISSUE TITLE
Open info for automated/group emails

### ISSUE THREAD

**Issue by lachlanrdale** [jasonlewis72/amcs#60]
Hey all,

Am I able to get information on who has opened and/or clicked on a particular email?

IE: I would like to extract a list of email addresses who have:

* Opened Group email - Fundraising chaser Flow 3 and 4
* Clicked Group email - Fundraising chaser Flow 3 and 4
* Opened Automation email - Engagement email 7 days after sign
* Clicked Automation email - Engagement email 7 days after sign

I can see there is a log for group emails where Opens are available. Is there a screen for the automation sends?

**Comment by bradmac** [comment]
You can get this from the email history for each of the automations. Just export to CSV from the email history tab, and then filter. Column B (Open Status) has either 'opened' if the email has been read or 'converted' if they followed a link to the site
